// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgOnyMC8Quh6LpL0nT9rOMXAcT8GHLS2k',
    appId: '1:947169492615:web:cc4f0bf710273e371fc222',
    messagingSenderId: '947169492615',
    projectId: 'zc-dodiddone-b8192',
    authDomain: 'zc-dodiddone-b8192.firebaseapp.com',
    storageBucket: 'zc-dodiddone-b8192.appspot.com',
    measurementId: 'G-YSNYZK8BC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7xQSVVOe7bp-BBKnI3jV1KawWvziftTs',
    appId: '1:947169492615:android:6f7f506bc8f947a11fc222',
    messagingSenderId: '947169492615',
    projectId: 'zc-dodiddone-b8192',
    storageBucket: 'zc-dodiddone-b8192.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSqMxhLRqWrqaNNCuTY8RUWMFZMCaLFgI',
    appId: '1:947169492615:ios:25124570fe53e0351fc222',
    messagingSenderId: '947169492615',
    projectId: 'zc-dodiddone-b8192',
    storageBucket: 'zc-dodiddone-b8192.appspot.com',
    iosBundleId: 'com.example.zcDodiddone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSqMxhLRqWrqaNNCuTY8RUWMFZMCaLFgI',
    appId: '1:947169492615:ios:25124570fe53e0351fc222',
    messagingSenderId: '947169492615',
    projectId: 'zc-dodiddone-b8192',
    storageBucket: 'zc-dodiddone-b8192.appspot.com',
    iosBundleId: 'com.example.zcDodiddone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgOnyMC8Quh6LpL0nT9rOMXAcT8GHLS2k',
    appId: '1:947169492615:web:d805825de55152681fc222',
    messagingSenderId: '947169492615',
    projectId: 'zc-dodiddone-b8192',
    authDomain: 'zc-dodiddone-b8192.firebaseapp.com',
    storageBucket: 'zc-dodiddone-b8192.appspot.com',
    measurementId: 'G-GTG74EVN7F',
  );
}